cargo-features = ["edition2024"]

[package]
name = "blurhash"
version = "0.3.0"
authors = ["Balazs Horvath <acsipont@gmail.com>"]
edition = "2024"
description = "A CLI application for generating BlurHash from images"
license = "MIT"

[dependencies]
image = "0.25.4"
clap = { version = "4.5.20", features = ["derive"] }
thiserror = "1.0.65"
tokio = { version = "1.41.0", features = ["full"] }
futures = "0.3.28"
num_cpus = "1.15.0"

[profile.release]
lto = true
