[package]
name = "blurhash"
version = "0.2.0"
authors = ["fpapado <fgpapado@gmail.com>"]
edition = "2018"

description = "A CLI application for generating BlurHash from images"
license = "MIT"

[dependencies]
image = "0.25.4"
clap = { version = "4.5.20", features = ["derive"] }
thiserror = "1.0.65"

[profile.release]
lto = true